version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak

  keycloak:
    image: dcm4che/keycloak:16.1.1
    depends_on:
      - db
    volumes:
      - keycloak:/tmp
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: quarkus
      KEYCLOAK_DB_USER: postgres
      KEYCLOAK_DB_PASSWORD: postgres
      DB_VENDOR: postgres
      DB_SCHEMA: public
    ports:
      - 8080:8080

volumes:
  postgresdata:
  keycloak: